OpenAPITools/openapi-generator-cli

bin/openapi-generator

It is necessary to detect generator failures from parent scripts, if
any.

Propagates generator exit code to the parent NodeJS process

---

bin/openapi-generator

Add "$JAVA_OPTS" to enable jvm options

---

bin/openapi-generator

The `exec()` function buffers the output of the command executed.
When using a large input spec (over 20k lines), the process is terminated due to overflowing the buffer.
Increasing the buffer also fixes the issue, but for a generic solution, `spawn()` pipes the output directly without buffering, and behaves just the same with the option `shell: true`.
To replicate the error, run `exec(command, { maxBuffer: 1000 })` on the [petstore example](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml).
More info on https://medium.freecodecamp.org/node-js-child-processes-everything-you-need-to-know-e69498fe970a.

Fixes shell buffer overflow for large input specs

---

package.json

The message looks like this:
```
npm install
> openapitools@0.0.0-development postinstall /Users/williamcheng/Code/openapi-generator-cli
> opencollective || exit 0
Thanks for installing openapi_generator 🙏
Please consider donating to our open collective
to help us maintain this package.
Number of contributors: 0
Number of backers: 18
Annual budget: $5,332
Current balance: $3,257
👉  Please sponsor OpenAPI Generator. https://opencollective.com/openapi_generator/donate
npm WARN @nestjs/schematics@7.1.2 requires a peer of typescript@^3.4.5 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.4.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is …
```

feat(core): add opencollective to to show sponsorship message

---

apps/generator-cli/src/app/services/version-manager.service.spec.ts
apps/generator-cli/src/app/services/version-manager.service.ts

This pull request allows the version manager to download multiple files concurrently of the same version. Currently, doing so corrupts the file because the downloaded stream overwrites the partially downloaded file of the other process.
Also see issue #188, which was closed.
The workaround presented in the issue is only a workaround and not a fix. The request to re-open the issue was unanswered, so I created a pull request instead.

feat: allow concurrent downloads by downloading file and moving it

---

apps/generator-cli/src/app/services/version-manager.service.spec.ts
apps/generator-cli/src/app/services/version-manager.service.ts
package.json
yarn.lock

This is a followup PR of https://github.com/OpenAPITools/openapi-generator-cli/pull/295. Concurrent downloads work well, but the filesystem move call throws an error in `fs-extra` when the file already exists... It should replace it of course.
Reference documentation: https://github.com/jprichardson/node-fs-extra/blob/master/docs/move-sync.md
Sorry I did not notice it in previous testing. All the tests currently mock the filesystem library, so I cannot simulate an existing file.
Example (anonymized) output of current 2.2.0 version:
```
...
Compile the schemas /XXXXXX/har.schema.yaml to /XXXXXX
Compiling /XXXXXX/har.schema.yaml with name har.
Compile the schemas /XXXXXX/index.schema.yaml to /XXXXXX/generated
Compiling /XXXXXX/index.schema.yaml with name Index.
Compile the schemas …
```

fix: add overwrite: true to overwrite on existing file

---

apps/generator-cli/src/README.md

This change fixes the typo "blow", changing it to "below".

Fix small typo in README

---

.husky/commit-msg
package.json

Fix broken husky hooks (since https://github.com/OpenAPITools/openapi-generator-cli/pull/316)
Converted husky v4 configuration to husky v7 config
Source: https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint-

chore: fix husky hooks

---

apps/generator-cli/src/app/services/generator.service.spec.ts
apps/generator-cli/src/app/services/generator.service.ts
apps/generator-cli/src/app/services/pass-through.service.spec.ts
apps/generator-cli/src/app/services/pass-through.service.ts

Fixes #439 
The `custom-generator` parameter was only working for simple passthrough command, passing `custom-generator` to the generate command allows it to be used alongside `-generator-key` parameters.

fix(#439): allow custom generator to be passed to the generate command

---

apps/generator-cli/src/app/services/generator.service.ts

This fixes generated clients being owned by root when using runDocker

fix: run docker with the --user argument

---

.github/workflows/build.yml
.github/workflows/release.yml
apps/generator-cli/src/app/app.module.ts
apps/generator-cli/src/app/services/generator.service.ts
apps/generator-cli/src/app/services/version-manager.service.spec.ts
apps/generator-cli/src/app/services/version-manager.service.ts
package.json
yarn.lock

As the new axios HttpModules respects the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY, there is no need to configure it explicitly anymore. 
This fixes issue #390

Replace deprecated HttpModule from @nestjs/common with @nestjs/axios

---

package.json
yarn.lock

`@nestjs/axios` `0.0.8` has a peer dependency on `@nestjs/common` `^7.0.0 || ^8.0.0` (https://github.com/nestjs/axios/blob/0.0.8/package.json#L49), but ` @openapitools/openapi-generator-cli` depends on `@nestjs/common` `9.3.11`, which fails strict peer dependency checks (e.g. NPM's [--strict-peer-deps](https://docs.npmjs.com/cli/v7/using-npm/config#strict-peer-deps) or PNPM's [strict-peer-dependencies](https://pnpm.io/npmrc#strict-peer-dependencies)).
`@nestjs/axios` `0.1+` supports `@nestjs/common` `^9.0.0` (https://github.com/nestjs/axios/blob/0.1.0/package.json#L49).
`3.0.0` is the latest version of `@nestjs/axios` that still supports `@nestjs/common` `9.3.11`, and meets all the other peer dependencies (https://github.com/nestjs/axios/blob/3.0.0/package.json#L48).

Fix @nestjs/axios version

---

apps/generator-cli/src/app/app.module.ts
apps/generator-cli/src/app/services/config.service.spec.ts
apps/generator-cli/src/app/services/config.service.ts

This PR adds a command line argument, `--openapitools`, that allows a user to provide an `openapitools.json` file from the command line.
The current version of the cli [hardcodes](https://github.com/OpenAPITools/openapi-generator-cli/blob/720b405fd0984b6e9b510358418ea1b80ea3113b/apps/generator-cli/src/app/services/config.service.ts#L11) the location of this file. 
Should resolve at least #644.
Disclaimer, I am not a typescript developer and did my best to get a feature I (and others seem to) need :)

feat(#644): add cli option for openapitools.json

---

apps/generator-cli/src/README.md

based on  #790 with minor changes

update versions mentioned in Readme

---

.github/workflows/build.yml
apps/generator-cli/src/app/services/version-manager.service.ts

add fallback to a list of default versions if maven search returns errors so that users can still use openapi-generator without issues using a fixed set of released versions (e.g. 7.7.0)
later we will return fixed set of released versions as the default and search maven as a fallback (or if OPENAPI_GENERATOR_CLI_SEARCH_URL is set to `https://search.maven.org`)
cc @kay-schecker

fix(#802): add fallback to default versions if search returns errors

---

.husky/commit-msg
package.json

Currently, when using this repo and trying to commit, this shows up:
and
(seen when opening #826)
references https://github.com/typicode/husky/issues/1480 and https://github.com/typicode/husky/releases/tag/v9.0.1#How%20to%20Migrate

chore: fix husky

---

package.json
yarn.lock

Currently, when using this package, a warning is shown:
It was mentioned here as well https://github.com/OpenAPITools/openapi-generator-cli/pull/789#issuecomment-2298777337 by @wing328 
The reason for these errors is because an old version of `glob` is pulled: 
```
npm why glob
glob@7.2.3
node_modules/glob
glob@"7.2.3" from @openapitools/openapi-generator-cli@2.13.12
node_modules/@openapitools/openapi-generator-cli
@openapitools/openapi-generator-cli@"^2.13.5" from the root project
```
it gets added to the package lock when generating the `dist` via `yarn build`.
The reason is that the `glob` package is used here: https://github.com/OpenAPITools/openapi-generator-cli/blob/113ee846c64c6cbda3107a010e7f975371e79b30/apps/generator-cli/src/app/services/generator.service.ts#L7 but the current …

fix: update `glob` package

---

.envrc
.gitignore
flake.lock
flake.nix

This adds a nix flake similar to the one we have in https://github.com/OpenAPITools/openapi-generator
It installs yarn 1.x and node 18 ~w/o npm~ and adds a direnv directive.
update: we need npm, it seems we use it here: https://github.com/OpenAPITools/openapi-generator-cli/blob/113ee846c64c6cbda3107a010e7f975371e79b30/package.json#L54 in addition to yarn
The current lock file sets this to:
```
node --version
v18.20.4
yarn --version
1.22.22
npm --version
10.7.0
```
same as in the current `master`: https://github.com/OpenAPITools/openapi-generator-cli/actions/runs/11091950012/job/30816360053

chore: add nix flake

---

apps/generator-cli/src/config.schema.json

add openapi-normalizer generator property in config file schema based on openAPI documentation : https://openapi-generator.tech/docs/customization/#openapi-normalizer
close #824

feat(config schema): add openapi-normalizer generator property

---

apps/generator-cli/src/app/app.module.ts
package.json
yarn.lock

Fixes a bug introduced in #762, where the "no-proxy" environment configuration was ignored.
With this PR I moved from the usage of `https-proxy-agent` to `proxy-agent`.  This was done as `https-proxy-agent` was configured to take the proxy url from the environment but the library itself doesn't handle `NO_PROXY` / `no_proxy` configuration.
`proxy-agent` on the other side, is sitting on top of the `https-proxy-agent` and `http-proxy-agent` library and decides if the proxy is used based on the request URL and the domains specified in the "no proxy" environment variables.
---
1. Set the configuration for your proxy in the usual environment variables `HTTP_PROXY` , `HTTPS_PROXY`, `http_proxy`, `https_proxy`, `NO_PROXY`, `no_proxy`.
2. You can set your custom repository download url in the …

fix(http): use proxy agent setup that supports proxy env variables with `no_proxy`

---

package.json
yarn.lock

This PR updates the Axios dependency 📦️ to fix (https://github.com/advisories/GHSA-4hjh-wcwx-xvwj) vulnerability.. The change was verified by running the initial CLI build/tests and confirming that client generation still works as expected.
🔍✅ The following test were performed to test the openapi-generator-cli 🚑️🔒️
Updated the Axios dependency
Ran the local build and CLI tests successfully.
Generated both TypeScript and Python clients from a custom test specification.
npm run cli -- generate -i samples/test.yaml -g typescript-fetch -o tmp-client
npm run cli -- generate -i samples/test.yaml -g python -o tmp-client
Verified that the generated clients were built correctly and run as expected without errors.
Environment
Node.js v22.14.0,
NPM 10.9.2
java version "24.0.2" 2025-07-15
Java(TM) SE …

📦️ update vulnerable axios package to ^1.12.0
